name: aseprite-skia-bin
on:
  push:
    paths:
        - "aseprite-skia-bin/**"
  pull_request:
    paths:
        - "aseprite-skia-bin/**"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build package
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: "aseprite-skia-bin"
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
          path: ${{ steps.makepkg.outputs.pkgfile0 }}
