name: hugetracker-bin
on:
  push:
    paths:
        - .github/workflows/hugetracker-bin.yml
        - "hugetracker-bin/**"
  pull_request:
    paths:
        - .github/workflows/hugetracker-bin.yml
        - "hugetracker-bin/**"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build package
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: "hugetracker-bin"
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
          path: ${{ steps.makepkg.outputs.pkgfile0 }}
