name: pymusiclooper
on:
  push:
    paths:
        - .github/workflows/pymusiclooper.yml
        - "pymusiclooper/**"
  pull_request:
    paths:
        - .github/workflows/pymusiclooper.yml
        - "pymusiclooper/**"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build package
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: "pymusiclooper"
        aurDeps: true
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
          path: ${{ steps.makepkg.outputs.pkgfile0 }}
