name: python-click-params
on:
  push:
    paths:
        - "python-click-params/**"
  pull_request:
    paths:
        - "python-click-params/**"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build package
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: "python-click-params"
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
          path: ${{ steps.makepkg.outputs.pkgfile0 }}
