name: trackerboy-git
on:
  push:
    paths:
        - .github/workflows/trackerboy-git.yaml
        - "trackerboy-git/**"
  pull_request:
    paths:
        - .github/workflows/trackerboy-git.yaml
        - "trackerboy-git/**"
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build package
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: "trackerboy-git"
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
          path: ${{ steps.makepkg.outputs.pkgfile0 }}
